### ISSUE TITLE
Appairage direct

### ISSUE THREAD

**Issue by Xavier-M** [maximushugus/Zigate-Legrand-with-Netatmo-HA#1]
Salut,

As-tu réussi à lier directement un interrupteur sans fil avec un module d'éclairage filaire ?

Merci

**Comment by maximushugus** [comment]
Oui, j'envoie ici la méthode cet après midi

**Comment by maximushugus** [comment]
Est ce que tu as une zigate USB ou une pizigate ?

**Comment by Xavier-M** [comment]
USB

**Comment by maximushugus** [comment]
Ok donc avec une zigate USB c'est assez facile : 
Il faut d'abord que les interrupteurs sans fils que l'on souhaite utiliser soient déjà appairée avec la zigate (comme n'importe quel autre appareil zigbee), de même que l'interrupteurs filaires.
Il faut récupérer leur IEEE : que l'on peut trouver dans home assistant dans les outils de développement ou dans la page zigate admin.

Il faut connecter la zigate sur un port USB d'un PC sous Windows.
Dans le gestionnaire de périphériques il faut repérer quel est le port COM associé à la zigate (ex COM3).
Il faut télécharger ce programme : [https://github.com/fairecasoimeme/ZiGate/raw/master/Tools/TestGUI_ZiGate_NXP-4.zip](url)
Puis l'extraire et lancer "ZGWUI".

![image](https://user-images.githubusercontent.com/36080343/79689220-9f9d3d00-8253-11ea-9f9a-8f642bf64ebc.png)
Cliquer sur "Settings"
![image](https://user-images.githubusercontent.com/36080343/79689235-b2177680-8253-11ea-9f92-a6719d5409b2.png)
Puis sélectionner dans la liste le bon port COM (il n'y en aura probablement qu'un, avec le "Baud rate à 115200 puis ok.
Puis cliquer sur "open port"
![image](https://user-images.githubusercontent.com/36080343/79689270-d7a48000-8253-11ea-833a-b6e2752b02b8.png)
Cliquer ensuite sur "Get Version".
Puis paramétrer le canal 11 et cliquez sur « Set CMSK », choisir « COORDINATOR » puis cliquez sur « Set Type » puis cliquez sur « Start NWK »
![image](https://user-images.githubusercontent.com/36080343/79689294-10dcf000-8254-11ea-83c6-5ce75978773b.png)

Maintenant la communication directe avec la zigate est établie.

Pour faire l'association d'un interrupteur sans fils sur un filaire également déja appairé à la zigate : 
1) s'assurer que l'inter sans fil n'est pas en veille : appuyer sur le bouton off par exemple.
2) dans les 5 secondes il faut faire le bind des cluster 6 puis 8 de la télécommande vers l'interrupteur filaire : remplir comme ci dessous, en 1 l'IEEE de l'inter legrand with netatmo sans fil, en 2 l'IEEE de l'interrupteur filaire, en 3 le cluster (08 et 06) en veillant à ne pas mettre les "0x" ou les premier "00" des IEEE, et en mettant dans le menu déroulant "IEEE" puis en cliquant sur le bouton "Bind"

![image](https://user-images.githubusercontent.com/36080343/79689353-88128400-8254-11ea-9462-bce2cfb4d7d1.png)

**Comment by maximushugus** [comment]
Avec cette méthode les interrupteurs sans fils sont liés aux filaires : même si la zigate ou home assistant sont éteins le lien persiste

**Comment by Xavier-M** [comment]
Merci beaucoup !! Je test dès que je retrouve mon inter...

**Comment by Xavier-M** [comment]
Enfin retrouvé mon inter... Ca marche parfaitement, merci beaucoup !
